name: smrd
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Python core
  - python=3.10
  - pip

  # Python packages
  - pandas=2.2.3
  - matplotlib=3.10.1
  - scikit-bio=0.6.3
  - biopython=1.85
  - tqdm=4.67.1
  - scikit-learn==1.6.1

  # R core and packages
  - r-base=4.4.2
  - r-tidyverse=2.0.0
  - r-rmarkdown=2.29

  # Development tools
  - black=25.1.0
  - flake8=7.1.2
  - pre-commit=4.1.0
