name: smrd
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Python core
  - python=3.10
  - pip
    - kaleido=0.2.1

  # Python packages
  - pandas=2.2.3
  - matplotlib=3.10.1
  - scikit-bio=0.6.3
  - biopython=1.85
  - tqdm=4.67.1
  - scikit-learn==1.6.1
  - kaleido-core=0.2.1

  # R core and packages
  - r-base=4.4.2
  - r-tidyverse=2.0.0
  - r-rmarkdown=2.29
  - r-gridextra=2.3
  - r-svglite=2.1.3
  - r-ape=5.8_1
  - r-wesanderson=0.3.7
  - r-plotly=4.10.4
  - r-reticulate=1.42.0
  - plotly=6.0.1

  # Development tools
  - black=25.1.0
  - flake8=7.1.2
  - pre-commit=4.1.0
